apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slw-dailycast-pvc
  namespace: sideline-wire-dailycast
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slw-nfs
  resources:
    requests:
      storage: 20Gi
