apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slw-dailycast.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "slw-dailycast.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  S3_BUCKET: {{ .Values.config.S3_BUCKET | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
