{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    app.kubernetes.io/name: {{ include "slw-dailycast.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
{{- range .Values.pvc.accessModes }}
    - {{ . }}
{{- end }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
{{- end }}
