apiVersion: v1
kind: Secret
metadata:
  name: slw-dailycast-secrets
  namespace: sideline-wire-dailycast
type: Opaque
stringData:
  MINIO_ENDPOINT: "http://minio.sideline-wire-dailycast.svc.cluster.local:9000"
  MINIO_ACCESS_KEY: "slwminioadmin"
  MINIO_SECRET_KEY: "slw-minio-secret-change-me"
  MINIO_SECURE: "false"
  PG_HOST: "postgres.sideline-wire-dailycast.svc.cluster.local"
  PG_PORT: "5432"
  PG_USER: "slw"
  PG_PASSWORD: "slw-postgres-password-change-me"
  PG_DB: "slw_dailycast"
  MLFLOW_TRACKING_URI: "http://mlflow.log-anomaly.svc.cluster.local:5000"
  PREFECT_API_URL: "http://prefect-server.sideline-wire-dailycast.svc.cluster.local:4200/api"
  LLM_ENDPOINT: ""
  LLM_API_KEY: ""
  LLM_MODEL: ""
  SPORTS_API_URL: ""
  SPORTS_API_KEY: ""
  NEWS_API_URL: ""
  NEWS_API_KEY: ""
  SPORTSDB_API_URL: "https://www.thesportsdb.com"
  SPORTSDB_API_KEY: ""
  ESPN_SITE_API_URL: "https://site.api.espn.com"
  ESPN_CORE_API_URL: "https://sports.core.api.espn.com"
  ESPN_SPORTS: "football/nfl,basketball/nba,baseball/mlb,hockey/nhl"
  NEWSAPI_URL: "https://newsapi.org/v2"
  NEWSAPI_API_KEY: ""
  GNEWS_URL: "https://gnews.io/api/v4"
  GNEWS_API_KEY: ""
